openapi: 3.0.0
paths:
  /categories:
    get:
      summary: Liste toutes les catégories
      tags: [Categories]
      responses:
        '200':
          description: Tableau de catégories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '500':
          $ref: '#/components/responses/ServerError'
    post:
      summary: Crée une nouvelle catégorie
      tags: [Categories]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '201':
          description: Catégorie créée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '500':
          $ref: '#/components/responses/ServerError'

  /categories/{id}:
    parameters:
      - $ref: '#/components/parameters/CategoryId'
    get:
      summary: Récupère une catégorie
      tags: [Categories]
      responses:
        '200':
          description: Catégorie trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
    put:
      summary: Met à jour une catégorie
      tags: [Categories]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '200':
          description: Catégorie mise à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
    delete:
      summary: Supprime une catégorie
      tags: [Categories]
      responses:
        '200':
          description: Catégorie supprimée
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Catégorie supprimée
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
